const currentProduct = {
  id: 4498498814089,
  title: 'Wallowa Lake',
  handle: 'wallowa-lake',
  description:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">Beautiful Wallowa Lake near Joseph, Oregon. In 2013, I came to this spot three days in a row waiting for a great sunrise to commemorate my first trip to the region.</div>\n<div class="sm-image-metadata-keywords"></div>',
  published_at: '2020-01-20T14:02:58-05:00',
  created_at: '2020-01-20T14:02:58-05:00',
  vendor: 'Cody Wilson Photography',
  type: '',
  tags: [],
  price: 9000,
  price_min: 9000,
  price_max: 75000,
  available: true,
  price_varies: true,
  compare_at_price: null,
  compare_at_price_min: 0,
  compare_at_price_max: 0,
  compare_at_price_varies: false,
  variants: [
    {
      id: 31905159774345,
      title: '8x12 / Photo Pearl Paper / Glossy',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Photo Pearl Paper / Glossy',
      public_title: '8x12 / Photo Pearl Paper / Glossy',
      options: ['8x12', 'Photo Pearl Paper', 'Glossy'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159807113,
      title: '8x12 / Photo Pearl Paper / Matte',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Photo Pearl Paper / Matte',
      public_title: '8x12 / Photo Pearl Paper / Matte',
      options: ['8x12', 'Photo Pearl Paper', 'Matte'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159839881,
      title: '8x12 / Photo Pearl Paper / Lustre',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Photo Pearl Paper / Lustre',
      public_title: '8x12 / Photo Pearl Paper / Lustre',
      options: ['8x12', 'Photo Pearl Paper', 'Lustre'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159872649,
      title: '8x12 / Metal / Glossy',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Metal / Glossy',
      public_title: '8x12 / Metal / Glossy',
      options: ['8x12', 'Metal', 'Glossy'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159905417,
      title: '8x12 / Metal / Matte',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Metal / Matte',
      public_title: '8x12 / Metal / Matte',
      options: ['8x12', 'Metal', 'Matte'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159938185,
      title: '8x12 / Metal / Lustre',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Metal / Lustre',
      public_title: '8x12 / Metal / Lustre',
      options: ['8x12', 'Metal', 'Lustre'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905159970953,
      title: '8x12 / Framed Triple Matte / Glossy',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Framed Triple Matte / Glossy',
      public_title: '8x12 / Framed Triple Matte / Glossy',
      options: ['8x12', 'Framed Triple Matte', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160003721,
      title: '8x12 / Framed Triple Matte / Matte',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Framed Triple Matte / Matte',
      public_title: '8x12 / Framed Triple Matte / Matte',
      options: ['8x12', 'Framed Triple Matte', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160036489,
      title: '8x12 / Framed Triple Matte / Lustre',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 8x12 / Framed Triple Matte / Lustre',
      public_title: '8x12 / Framed Triple Matte / Lustre',
      options: ['8x12', 'Framed Triple Matte', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160069257,
      title: '12x18 / Photo Pearl Paper / Glossy',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Photo Pearl Paper / Glossy',
      public_title: '12x18 / Photo Pearl Paper / Glossy',
      options: ['12x18', 'Photo Pearl Paper', 'Glossy'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160102025,
      title: '12x18 / Photo Pearl Paper / Matte',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Photo Pearl Paper / Matte',
      public_title: '12x18 / Photo Pearl Paper / Matte',
      options: ['12x18', 'Photo Pearl Paper', 'Matte'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160134793,
      title: '12x18 / Photo Pearl Paper / Lustre',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Photo Pearl Paper / Lustre',
      public_title: '12x18 / Photo Pearl Paper / Lustre',
      options: ['12x18', 'Photo Pearl Paper', 'Lustre'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160167561,
      title: '12x18 / Metal / Glossy',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Metal / Glossy',
      public_title: '12x18 / Metal / Glossy',
      options: ['12x18', 'Metal', 'Glossy'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160200329,
      title: '12x18 / Metal / Matte',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Metal / Matte',
      public_title: '12x18 / Metal / Matte',
      options: ['12x18', 'Metal', 'Matte'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160233097,
      title: '12x18 / Metal / Lustre',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Metal / Lustre',
      public_title: '12x18 / Metal / Lustre',
      options: ['12x18', 'Metal', 'Lustre'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160265865,
      title: '12x18 / Framed Triple Matte / Glossy',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Framed Triple Matte / Glossy',
      public_title: '12x18 / Framed Triple Matte / Glossy',
      options: ['12x18', 'Framed Triple Matte', 'Glossy'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160298633,
      title: '12x18 / Framed Triple Matte / Matte',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Framed Triple Matte / Matte',
      public_title: '12x18 / Framed Triple Matte / Matte',
      options: ['12x18', 'Framed Triple Matte', 'Matte'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160331401,
      title: '12x18 / Framed Triple Matte / Lustre',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 12x18 / Framed Triple Matte / Lustre',
      public_title: '12x18 / Framed Triple Matte / Lustre',
      options: ['12x18', 'Framed Triple Matte', 'Lustre'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160364169,
      title: '16x24 / Photo Pearl Paper / Glossy',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Photo Pearl Paper / Glossy',
      public_title: '16x24 / Photo Pearl Paper / Glossy',
      options: ['16x24', 'Photo Pearl Paper', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160396937,
      title: '16x24 / Photo Pearl Paper / Matte',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Photo Pearl Paper / Matte',
      public_title: '16x24 / Photo Pearl Paper / Matte',
      options: ['16x24', 'Photo Pearl Paper', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160429705,
      title: '16x24 / Photo Pearl Paper / Lustre',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Photo Pearl Paper / Lustre',
      public_title: '16x24 / Photo Pearl Paper / Lustre',
      options: ['16x24', 'Photo Pearl Paper', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160462473,
      title: '16x24 / Metal / Glossy',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Metal / Glossy',
      public_title: '16x24 / Metal / Glossy',
      options: ['16x24', 'Metal', 'Glossy'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160495241,
      title: '16x24 / Metal / Matte',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Metal / Matte',
      public_title: '16x24 / Metal / Matte',
      options: ['16x24', 'Metal', 'Matte'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160528009,
      title: '16x24 / Metal / Lustre',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Metal / Lustre',
      public_title: '16x24 / Metal / Lustre',
      options: ['16x24', 'Metal', 'Lustre'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160560777,
      title: '16x24 / Framed Triple Matte / Glossy',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Framed Triple Matte / Glossy',
      public_title: '16x24 / Framed Triple Matte / Glossy',
      options: ['16x24', 'Framed Triple Matte', 'Glossy'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160593545,
      title: '16x24 / Framed Triple Matte / Matte',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Framed Triple Matte / Matte',
      public_title: '16x24 / Framed Triple Matte / Matte',
      options: ['16x24', 'Framed Triple Matte', 'Matte'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160626313,
      title: '16x24 / Framed Triple Matte / Lustre',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 16x24 / Framed Triple Matte / Lustre',
      public_title: '16x24 / Framed Triple Matte / Lustre',
      options: ['16x24', 'Framed Triple Matte', 'Lustre'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160659081,
      title: '20x30 / Photo Pearl Paper / Glossy',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Photo Pearl Paper / Glossy',
      public_title: '20x30 / Photo Pearl Paper / Glossy',
      options: ['20x30', 'Photo Pearl Paper', 'Glossy'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160691849,
      title: '20x30 / Photo Pearl Paper / Matte',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Photo Pearl Paper / Matte',
      public_title: '20x30 / Photo Pearl Paper / Matte',
      options: ['20x30', 'Photo Pearl Paper', 'Matte'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160724617,
      title: '20x30 / Photo Pearl Paper / Lustre',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Photo Pearl Paper / Lustre',
      public_title: '20x30 / Photo Pearl Paper / Lustre',
      options: ['20x30', 'Photo Pearl Paper', 'Lustre'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160757385,
      title: '20x30 / Metal / Glossy',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Metal / Glossy',
      public_title: '20x30 / Metal / Glossy',
      options: ['20x30', 'Metal', 'Glossy'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160790153,
      title: '20x30 / Metal / Matte',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Metal / Matte',
      public_title: '20x30 / Metal / Matte',
      options: ['20x30', 'Metal', 'Matte'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160822921,
      title: '20x30 / Metal / Lustre',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Metal / Lustre',
      public_title: '20x30 / Metal / Lustre',
      options: ['20x30', 'Metal', 'Lustre'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160855689,
      title: '20x30 / Framed Triple Matte / Glossy',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Framed Triple Matte / Glossy',
      public_title: '20x30 / Framed Triple Matte / Glossy',
      options: ['20x30', 'Framed Triple Matte', 'Glossy'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160888457,
      title: '20x30 / Framed Triple Matte / Matte',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Framed Triple Matte / Matte',
      public_title: '20x30 / Framed Triple Matte / Matte',
      options: ['20x30', 'Framed Triple Matte', 'Matte'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160921225,
      title: '20x30 / Framed Triple Matte / Lustre',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 20x30 / Framed Triple Matte / Lustre',
      public_title: '20x30 / Framed Triple Matte / Lustre',
      options: ['20x30', 'Framed Triple Matte', 'Lustre'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160953993,
      title: '24x36 / Photo Pearl Paper / Glossy',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Photo Pearl Paper / Glossy',
      public_title: '24x36 / Photo Pearl Paper / Glossy',
      options: ['24x36', 'Photo Pearl Paper', 'Glossy'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905160986761,
      title: '24x36 / Photo Pearl Paper / Matte',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Photo Pearl Paper / Matte',
      public_title: '24x36 / Photo Pearl Paper / Matte',
      options: ['24x36', 'Photo Pearl Paper', 'Matte'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161019529,
      title: '24x36 / Photo Pearl Paper / Lustre',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Photo Pearl Paper / Lustre',
      public_title: '24x36 / Photo Pearl Paper / Lustre',
      options: ['24x36', 'Photo Pearl Paper', 'Lustre'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161052297,
      title: '24x36 / Metal / Glossy',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Metal / Glossy',
      public_title: '24x36 / Metal / Glossy',
      options: ['24x36', 'Metal', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161085065,
      title: '24x36 / Metal / Matte',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Metal / Matte',
      public_title: '24x36 / Metal / Matte',
      options: ['24x36', 'Metal', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161117833,
      title: '24x36 / Metal / Lustre',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Metal / Lustre',
      public_title: '24x36 / Metal / Lustre',
      options: ['24x36', 'Metal', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161150601,
      title: '24x36 / Framed Triple Matte / Glossy',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Framed Triple Matte / Glossy',
      public_title: '24x36 / Framed Triple Matte / Glossy',
      options: ['24x36', 'Framed Triple Matte', 'Glossy'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161183369,
      title: '24x36 / Framed Triple Matte / Matte',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Framed Triple Matte / Matte',
      public_title: '24x36 / Framed Triple Matte / Matte',
      options: ['24x36', 'Framed Triple Matte', 'Matte'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161216137,
      title: '24x36 / Framed Triple Matte / Lustre',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 24x36 / Framed Triple Matte / Lustre',
      public_title: '24x36 / Framed Triple Matte / Lustre',
      options: ['24x36', 'Framed Triple Matte', 'Lustre'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161248905,
      title: '30x45 / Photo Pearl Paper / Glossy',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Photo Pearl Paper / Glossy',
      public_title: '30x45 / Photo Pearl Paper / Glossy',
      options: ['30x45', 'Photo Pearl Paper', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161281673,
      title: '30x45 / Photo Pearl Paper / Matte',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Photo Pearl Paper / Matte',
      public_title: '30x45 / Photo Pearl Paper / Matte',
      options: ['30x45', 'Photo Pearl Paper', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161314441,
      title: '30x45 / Photo Pearl Paper / Lustre',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Photo Pearl Paper / Lustre',
      public_title: '30x45 / Photo Pearl Paper / Lustre',
      options: ['30x45', 'Photo Pearl Paper', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161347209,
      title: '30x45 / Metal / Glossy',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Metal / Glossy',
      public_title: '30x45 / Metal / Glossy',
      options: ['30x45', 'Metal', 'Glossy'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161379977,
      title: '30x45 / Metal / Matte',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Metal / Matte',
      public_title: '30x45 / Metal / Matte',
      options: ['30x45', 'Metal', 'Matte'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161412745,
      title: '30x45 / Metal / Lustre',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Metal / Lustre',
      public_title: '30x45 / Metal / Lustre',
      options: ['30x45', 'Metal', 'Lustre'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161445513,
      title: '30x45 / Framed Triple Matte / Glossy',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Framed Triple Matte / Glossy',
      public_title: '30x45 / Framed Triple Matte / Glossy',
      options: ['30x45', 'Framed Triple Matte', 'Glossy'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161478281,
      title: '30x45 / Framed Triple Matte / Matte',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Framed Triple Matte / Matte',
      public_title: '30x45 / Framed Triple Matte / Matte',
      options: ['30x45', 'Framed Triple Matte', 'Matte'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31905161511049,
      title: '30x45 / Framed Triple Matte / Lustre',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Wallowa Lake - 30x45 / Framed Triple Matte / Lustre',
      public_title: '30x45 / Framed Triple Matte / Lustre',
      options: ['30x45', 'Framed Triple Matte', 'Lustre'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
  ],
  images: [
    '//cdn.shopify.com/s/files/1/0277/4394/4841/products/Wallowa_Sunrise_36x24_48dc7a4c-5057-4617-800a-0a5f67f1da8b.jpg?v=1579547041',
  ],
  featured_image:
    '//cdn.shopify.com/s/files/1/0277/4394/4841/products/Wallowa_Sunrise_36x24_48dc7a4c-5057-4617-800a-0a5f67f1da8b.jpg?v=1579547041',
  options: ['Size', 'Material', 'Finish'],
  media: [
    {
      alt: null,
      id: 6300377645193,
      position: 1,
      preview_image: {
        aspect_ratio: 1.5,
        height: 1365,
        width: 2048,
        src:
          'https://cdn.shopify.com/s/files/1/0277/4394/4841/products/Wallowa_Sunrise_36x24_48dc7a4c-5057-4617-800a-0a5f67f1da8b.jpg?v=1579547041',
      },
      aspect_ratio: 1.5,
      height: 1365,
      media_type: 'image',
      src:
        'https://cdn.shopify.com/s/files/1/0277/4394/4841/products/Wallowa_Sunrise_36x24_48dc7a4c-5057-4617-800a-0a5f67f1da8b.jpg?v=1579547041',
      width: 2048,
    },
  ],
  requires_selling_plan: false,
  selling_plan_groups: [],
  content:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">Beautiful Wallowa Lake near Joseph, Oregon. In 2013, I came to this spot three days in a row waiting for a great sunrise to commemorate my first trip to the region.</div>\n<div class="sm-image-metadata-keywords"></div>',
}

export { currentProduct }
