const currentProduct = {
  id: 4498847137929,
  title: 'Peter Iredale',
  handle: 'peter-iredale',
  description:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">The remains of a ship from the 1920s after it ran ashore in Northern Oregon.</div>\n<div class="sm-image-metadata-keywords"></div>',
  published_at: '2020-01-20T16:06:47-05:00',
  created_at: '2020-01-20T16:06:47-05:00',
  vendor: 'Cody Wilson Photography',
  type: '',
  tags: [],
  price: 9000,
  price_min: 9000,
  price_max: 75000,
  available: true,
  price_varies: true,
  compare_at_price: null,
  compare_at_price_min: 0,
  compare_at_price_max: 0,
  compare_at_price_varies: false,
  variants: [
    {
      id: 31907169009801,
      title: '8x12 / Photo Pearl Paper / Glossy',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Glossy',
      public_title: '8x12 / Photo Pearl Paper / Glossy',
      options: ['8x12', 'Photo Pearl Paper', 'Glossy'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169042569,
      title: '8x12 / Photo Pearl Paper / Matte',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Matte',
      public_title: '8x12 / Photo Pearl Paper / Matte',
      options: ['8x12', 'Photo Pearl Paper', 'Matte'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169075337,
      title: '8x12 / Photo Pearl Paper / Lustre',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Lustre',
      public_title: '8x12 / Photo Pearl Paper / Lustre',
      options: ['8x12', 'Photo Pearl Paper', 'Lustre'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169108105,
      title: '8x12 / Metal / Glossy',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Glossy',
      public_title: '8x12 / Metal / Glossy',
      options: ['8x12', 'Metal', 'Glossy'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169140873,
      title: '8x12 / Metal / Matte',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Matte',
      public_title: '8x12 / Metal / Matte',
      options: ['8x12', 'Metal', 'Matte'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169173641,
      title: '8x12 / Metal / Lustre',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Lustre',
      public_title: '8x12 / Metal / Lustre',
      options: ['8x12', 'Metal', 'Lustre'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169206409,
      title: '8x12 / Framed Triple Matte / Glossy',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Glossy',
      public_title: '8x12 / Framed Triple Matte / Glossy',
      options: ['8x12', 'Framed Triple Matte', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169239177,
      title: '8x12 / Framed Triple Matte / Matte',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Matte',
      public_title: '8x12 / Framed Triple Matte / Matte',
      options: ['8x12', 'Framed Triple Matte', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169271945,
      title: '8x12 / Framed Triple Matte / Lustre',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Lustre',
      public_title: '8x12 / Framed Triple Matte / Lustre',
      options: ['8x12', 'Framed Triple Matte', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169304713,
      title: '12x18 / Photo Pearl Paper / Glossy',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Glossy',
      public_title: '12x18 / Photo Pearl Paper / Glossy',
      options: ['12x18', 'Photo Pearl Paper', 'Glossy'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169337481,
      title: '12x18 / Photo Pearl Paper / Matte',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Matte',
      public_title: '12x18 / Photo Pearl Paper / Matte',
      options: ['12x18', 'Photo Pearl Paper', 'Matte'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169370249,
      title: '12x18 / Photo Pearl Paper / Lustre',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Lustre',
      public_title: '12x18 / Photo Pearl Paper / Lustre',
      options: ['12x18', 'Photo Pearl Paper', 'Lustre'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169403017,
      title: '12x18 / Metal / Glossy',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Glossy',
      public_title: '12x18 / Metal / Glossy',
      options: ['12x18', 'Metal', 'Glossy'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169435785,
      title: '12x18 / Metal / Matte',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Matte',
      public_title: '12x18 / Metal / Matte',
      options: ['12x18', 'Metal', 'Matte'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169468553,
      title: '12x18 / Metal / Lustre',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Lustre',
      public_title: '12x18 / Metal / Lustre',
      options: ['12x18', 'Metal', 'Lustre'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169501321,
      title: '12x18 / Framed Triple Matte / Glossy',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Glossy',
      public_title: '12x18 / Framed Triple Matte / Glossy',
      options: ['12x18', 'Framed Triple Matte', 'Glossy'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169534089,
      title: '12x18 / Framed Triple Matte / Matte',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Matte',
      public_title: '12x18 / Framed Triple Matte / Matte',
      options: ['12x18', 'Framed Triple Matte', 'Matte'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169566857,
      title: '12x18 / Framed Triple Matte / Lustre',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Lustre',
      public_title: '12x18 / Framed Triple Matte / Lustre',
      options: ['12x18', 'Framed Triple Matte', 'Lustre'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169599625,
      title: '16x24 / Photo Pearl Paper / Glossy',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Glossy',
      public_title: '16x24 / Photo Pearl Paper / Glossy',
      options: ['16x24', 'Photo Pearl Paper', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169632393,
      title: '16x24 / Photo Pearl Paper / Matte',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Matte',
      public_title: '16x24 / Photo Pearl Paper / Matte',
      options: ['16x24', 'Photo Pearl Paper', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169665161,
      title: '16x24 / Photo Pearl Paper / Lustre',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Lustre',
      public_title: '16x24 / Photo Pearl Paper / Lustre',
      options: ['16x24', 'Photo Pearl Paper', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169697929,
      title: '16x24 / Metal / Glossy',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Glossy',
      public_title: '16x24 / Metal / Glossy',
      options: ['16x24', 'Metal', 'Glossy'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169730697,
      title: '16x24 / Metal / Matte',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Matte',
      public_title: '16x24 / Metal / Matte',
      options: ['16x24', 'Metal', 'Matte'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169796233,
      title: '16x24 / Metal / Lustre',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Lustre',
      public_title: '16x24 / Metal / Lustre',
      options: ['16x24', 'Metal', 'Lustre'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169829001,
      title: '16x24 / Framed Triple Matte / Glossy',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Glossy',
      public_title: '16x24 / Framed Triple Matte / Glossy',
      options: ['16x24', 'Framed Triple Matte', 'Glossy'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169861769,
      title: '16x24 / Framed Triple Matte / Matte',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Matte',
      public_title: '16x24 / Framed Triple Matte / Matte',
      options: ['16x24', 'Framed Triple Matte', 'Matte'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169894537,
      title: '16x24 / Framed Triple Matte / Lustre',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Lustre',
      public_title: '16x24 / Framed Triple Matte / Lustre',
      options: ['16x24', 'Framed Triple Matte', 'Lustre'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169927305,
      title: '20x30 / Photo Pearl Paper / Glossy',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Glossy',
      public_title: '20x30 / Photo Pearl Paper / Glossy',
      options: ['20x30', 'Photo Pearl Paper', 'Glossy'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169960073,
      title: '20x30 / Photo Pearl Paper / Matte',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Matte',
      public_title: '20x30 / Photo Pearl Paper / Matte',
      options: ['20x30', 'Photo Pearl Paper', 'Matte'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169992841,
      title: '20x30 / Photo Pearl Paper / Lustre',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Lustre',
      public_title: '20x30 / Photo Pearl Paper / Lustre',
      options: ['20x30', 'Photo Pearl Paper', 'Lustre'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170025609,
      title: '20x30 / Metal / Glossy',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Glossy',
      public_title: '20x30 / Metal / Glossy',
      options: ['20x30', 'Metal', 'Glossy'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170058377,
      title: '20x30 / Metal / Matte',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Matte',
      public_title: '20x30 / Metal / Matte',
      options: ['20x30', 'Metal', 'Matte'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170091145,
      title: '20x30 / Metal / Lustre',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Lustre',
      public_title: '20x30 / Metal / Lustre',
      options: ['20x30', 'Metal', 'Lustre'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170123913,
      title: '20x30 / Framed Triple Matte / Glossy',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Glossy',
      public_title: '20x30 / Framed Triple Matte / Glossy',
      options: ['20x30', 'Framed Triple Matte', 'Glossy'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170156681,
      title: '20x30 / Framed Triple Matte / Matte',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Matte',
      public_title: '20x30 / Framed Triple Matte / Matte',
      options: ['20x30', 'Framed Triple Matte', 'Matte'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170189449,
      title: '20x30 / Framed Triple Matte / Lustre',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Lustre',
      public_title: '20x30 / Framed Triple Matte / Lustre',
      options: ['20x30', 'Framed Triple Matte', 'Lustre'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170222217,
      title: '24x36 / Photo Pearl Paper / Glossy',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Glossy',
      public_title: '24x36 / Photo Pearl Paper / Glossy',
      options: ['24x36', 'Photo Pearl Paper', 'Glossy'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170254985,
      title: '24x36 / Photo Pearl Paper / Matte',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Matte',
      public_title: '24x36 / Photo Pearl Paper / Matte',
      options: ['24x36', 'Photo Pearl Paper', 'Matte'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170287753,
      title: '24x36 / Photo Pearl Paper / Lustre',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Lustre',
      public_title: '24x36 / Photo Pearl Paper / Lustre',
      options: ['24x36', 'Photo Pearl Paper', 'Lustre'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170320521,
      title: '24x36 / Metal / Glossy',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Glossy',
      public_title: '24x36 / Metal / Glossy',
      options: ['24x36', 'Metal', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170353289,
      title: '24x36 / Metal / Matte',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Matte',
      public_title: '24x36 / Metal / Matte',
      options: ['24x36', 'Metal', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170386057,
      title: '24x36 / Metal / Lustre',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Lustre',
      public_title: '24x36 / Metal / Lustre',
      options: ['24x36', 'Metal', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170418825,
      title: '24x36 / Framed Triple Matte / Glossy',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Glossy',
      public_title: '24x36 / Framed Triple Matte / Glossy',
      options: ['24x36', 'Framed Triple Matte', 'Glossy'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170451593,
      title: '24x36 / Framed Triple Matte / Matte',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Matte',
      public_title: '24x36 / Framed Triple Matte / Matte',
      options: ['24x36', 'Framed Triple Matte', 'Matte'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170484361,
      title: '24x36 / Framed Triple Matte / Lustre',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Lustre',
      public_title: '24x36 / Framed Triple Matte / Lustre',
      options: ['24x36', 'Framed Triple Matte', 'Lustre'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170549897,
      title: '30x45 / Photo Pearl Paper / Glossy',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Glossy',
      public_title: '30x45 / Photo Pearl Paper / Glossy',
      options: ['30x45', 'Photo Pearl Paper', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170648201,
      title: '30x45 / Photo Pearl Paper / Matte',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Matte',
      public_title: '30x45 / Photo Pearl Paper / Matte',
      options: ['30x45', 'Photo Pearl Paper', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170713737,
      title: '30x45 / Photo Pearl Paper / Lustre',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Lustre',
      public_title: '30x45 / Photo Pearl Paper / Lustre',
      options: ['30x45', 'Photo Pearl Paper', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170746505,
      title: '30x45 / Metal / Glossy',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Glossy',
      public_title: '30x45 / Metal / Glossy',
      options: ['30x45', 'Metal', 'Glossy'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170812041,
      title: '30x45 / Metal / Matte',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Matte',
      public_title: '30x45 / Metal / Matte',
      options: ['30x45', 'Metal', 'Matte'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170877577,
      title: '30x45 / Metal / Lustre',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Lustre',
      public_title: '30x45 / Metal / Lustre',
      options: ['30x45', 'Metal', 'Lustre'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170943113,
      title: '30x45 / Framed Triple Matte / Glossy',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Glossy',
      public_title: '30x45 / Framed Triple Matte / Glossy',
      options: ['30x45', 'Framed Triple Matte', 'Glossy'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907171008649,
      title: '30x45 / Framed Triple Matte / Matte',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Matte',
      public_title: '30x45 / Framed Triple Matte / Matte',
      options: ['30x45', 'Framed Triple Matte', 'Matte'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907171074185,
      title: '30x45 / Framed Triple Matte / Lustre',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Lustre',
      public_title: '30x45 / Framed Triple Matte / Lustre',
      options: ['30x45', 'Framed Triple Matte', 'Lustre'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
  ],
  images: [
    'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
  ],
  featured_image:
    'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
  options: ['Size', 'Material', 'Finish'],
  media: [
    {
      alt: null,
      id: 6302027022473,
      position: 1,
      preview_image: {
        aspect_ratio: 2,
        height: 2,
        width: 3,
        src:
          'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
      },
      aspect_ratio: 2,
      height: 1024,
      media_type: 'image',
      src:
        'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
      width: 2048,
    },
  ],
  requires_selling_plan: false,
  selling_plan_groups: [],
  content:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">The remains of a ship from the 1920s after it ran ashore in Northern Oregon.</div>\n<div class="sm-image-metadata-keywords"></div>',
  selected: {
    id: 31907169009801,
    title: '8x12 / Photo Pearl Paper / Glossy',
    option1: '8x12',
    option2: 'Photo Pearl Paper',
    option3: 'Glossy',
    sku: '',
    requires_shipping: false,
    taxable: false,
    featured_image: null,
    available: true,
    name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Glossy',
    public_title: '8x12 / Photo Pearl Paper / Glossy',
    options: ['8x12', 'Photo Pearl Paper', 'Glossy'],
    price: 9000,
    weight: 0,
    compare_at_price: null,
    inventory_management: null,
    barcode: '',
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  optionsWithValues: [
    {
      name: 'Size',
      position: 1,
      values: ['8x12', '12x18', '16x24', '20x30', '24x36', '30x45'],
    },
    {
      name: 'Material',
      position: 2,
      values: ['Photo Pearl Paper', 'Metal', 'Framed Triple Matte'],
    },
    {
      name: 'Finish',
      position: 3,
      values: ['Glossy', 'Matte', 'Lustre'],
    },
  ],
}

const portraitProduct = {
  id: 4498847137929,
  title: 'Peter Iredale',
  handle: 'peter-iredale',
  description:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">The remains of a ship from the 1920s after it ran ashore in Northern Oregon.</div>\n<div class="sm-image-metadata-keywords"></div>',
  published_at: '2020-01-20T16:06:47-05:00',
  created_at: '2020-01-20T16:06:47-05:00',
  vendor: 'Cody Wilson Photography',
  type: '',
  tags: [],
  price: 9000,
  price_min: 9000,
  price_max: 75000,
  available: true,
  price_varies: true,
  compare_at_price: null,
  compare_at_price_min: 0,
  compare_at_price_max: 0,
  compare_at_price_varies: false,
  variants: [
    {
      id: 31907169009801,
      title: '8x12 / Photo Pearl Paper / Glossy',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Glossy',
      public_title: '8x12 / Photo Pearl Paper / Glossy',
      options: ['8x12', 'Photo Pearl Paper', 'Glossy'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169042569,
      title: '8x12 / Photo Pearl Paper / Matte',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Matte',
      public_title: '8x12 / Photo Pearl Paper / Matte',
      options: ['8x12', 'Photo Pearl Paper', 'Matte'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169075337,
      title: '8x12 / Photo Pearl Paper / Lustre',
      option1: '8x12',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Lustre',
      public_title: '8x12 / Photo Pearl Paper / Lustre',
      options: ['8x12', 'Photo Pearl Paper', 'Lustre'],
      price: 9000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169108105,
      title: '8x12 / Metal / Glossy',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Glossy',
      public_title: '8x12 / Metal / Glossy',
      options: ['8x12', 'Metal', 'Glossy'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169140873,
      title: '8x12 / Metal / Matte',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Matte',
      public_title: '8x12 / Metal / Matte',
      options: ['8x12', 'Metal', 'Matte'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169173641,
      title: '8x12 / Metal / Lustre',
      option1: '8x12',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Metal / Lustre',
      public_title: '8x12 / Metal / Lustre',
      options: ['8x12', 'Metal', 'Lustre'],
      price: 16000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169206409,
      title: '8x12 / Framed Triple Matte / Glossy',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Glossy',
      public_title: '8x12 / Framed Triple Matte / Glossy',
      options: ['8x12', 'Framed Triple Matte', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169239177,
      title: '8x12 / Framed Triple Matte / Matte',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Matte',
      public_title: '8x12 / Framed Triple Matte / Matte',
      options: ['8x12', 'Framed Triple Matte', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169271945,
      title: '8x12 / Framed Triple Matte / Lustre',
      option1: '8x12',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 8x12 / Framed Triple Matte / Lustre',
      public_title: '8x12 / Framed Triple Matte / Lustre',
      options: ['8x12', 'Framed Triple Matte', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169304713,
      title: '12x18 / Photo Pearl Paper / Glossy',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Glossy',
      public_title: '12x18 / Photo Pearl Paper / Glossy',
      options: ['12x18', 'Photo Pearl Paper', 'Glossy'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169337481,
      title: '12x18 / Photo Pearl Paper / Matte',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Matte',
      public_title: '12x18 / Photo Pearl Paper / Matte',
      options: ['12x18', 'Photo Pearl Paper', 'Matte'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169370249,
      title: '12x18 / Photo Pearl Paper / Lustre',
      option1: '12x18',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Photo Pearl Paper / Lustre',
      public_title: '12x18 / Photo Pearl Paper / Lustre',
      options: ['12x18', 'Photo Pearl Paper', 'Lustre'],
      price: 12000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169403017,
      title: '12x18 / Metal / Glossy',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Glossy',
      public_title: '12x18 / Metal / Glossy',
      options: ['12x18', 'Metal', 'Glossy'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169435785,
      title: '12x18 / Metal / Matte',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Matte',
      public_title: '12x18 / Metal / Matte',
      options: ['12x18', 'Metal', 'Matte'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169468553,
      title: '12x18 / Metal / Lustre',
      option1: '12x18',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Metal / Lustre',
      public_title: '12x18 / Metal / Lustre',
      options: ['12x18', 'Metal', 'Lustre'],
      price: 21000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169501321,
      title: '12x18 / Framed Triple Matte / Glossy',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Glossy',
      public_title: '12x18 / Framed Triple Matte / Glossy',
      options: ['12x18', 'Framed Triple Matte', 'Glossy'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169534089,
      title: '12x18 / Framed Triple Matte / Matte',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Matte',
      public_title: '12x18 / Framed Triple Matte / Matte',
      options: ['12x18', 'Framed Triple Matte', 'Matte'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169566857,
      title: '12x18 / Framed Triple Matte / Lustre',
      option1: '12x18',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 12x18 / Framed Triple Matte / Lustre',
      public_title: '12x18 / Framed Triple Matte / Lustre',
      options: ['12x18', 'Framed Triple Matte', 'Lustre'],
      price: 22500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169599625,
      title: '16x24 / Photo Pearl Paper / Glossy',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Glossy',
      public_title: '16x24 / Photo Pearl Paper / Glossy',
      options: ['16x24', 'Photo Pearl Paper', 'Glossy'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169632393,
      title: '16x24 / Photo Pearl Paper / Matte',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Matte',
      public_title: '16x24 / Photo Pearl Paper / Matte',
      options: ['16x24', 'Photo Pearl Paper', 'Matte'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169665161,
      title: '16x24 / Photo Pearl Paper / Lustre',
      option1: '16x24',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Photo Pearl Paper / Lustre',
      public_title: '16x24 / Photo Pearl Paper / Lustre',
      options: ['16x24', 'Photo Pearl Paper', 'Lustre'],
      price: 17500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169697929,
      title: '16x24 / Metal / Glossy',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Glossy',
      public_title: '16x24 / Metal / Glossy',
      options: ['16x24', 'Metal', 'Glossy'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169730697,
      title: '16x24 / Metal / Matte',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Matte',
      public_title: '16x24 / Metal / Matte',
      options: ['16x24', 'Metal', 'Matte'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169796233,
      title: '16x24 / Metal / Lustre',
      option1: '16x24',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Metal / Lustre',
      public_title: '16x24 / Metal / Lustre',
      options: ['16x24', 'Metal', 'Lustre'],
      price: 26000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169829001,
      title: '16x24 / Framed Triple Matte / Glossy',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Glossy',
      public_title: '16x24 / Framed Triple Matte / Glossy',
      options: ['16x24', 'Framed Triple Matte', 'Glossy'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169861769,
      title: '16x24 / Framed Triple Matte / Matte',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Matte',
      public_title: '16x24 / Framed Triple Matte / Matte',
      options: ['16x24', 'Framed Triple Matte', 'Matte'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169894537,
      title: '16x24 / Framed Triple Matte / Lustre',
      option1: '16x24',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 16x24 / Framed Triple Matte / Lustre',
      public_title: '16x24 / Framed Triple Matte / Lustre',
      options: ['16x24', 'Framed Triple Matte', 'Lustre'],
      price: 30000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169927305,
      title: '20x30 / Photo Pearl Paper / Glossy',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Glossy',
      public_title: '20x30 / Photo Pearl Paper / Glossy',
      options: ['20x30', 'Photo Pearl Paper', 'Glossy'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169960073,
      title: '20x30 / Photo Pearl Paper / Matte',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Matte',
      public_title: '20x30 / Photo Pearl Paper / Matte',
      options: ['20x30', 'Photo Pearl Paper', 'Matte'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907169992841,
      title: '20x30 / Photo Pearl Paper / Lustre',
      option1: '20x30',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Photo Pearl Paper / Lustre',
      public_title: '20x30 / Photo Pearl Paper / Lustre',
      options: ['20x30', 'Photo Pearl Paper', 'Lustre'],
      price: 27500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170025609,
      title: '20x30 / Metal / Glossy',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Glossy',
      public_title: '20x30 / Metal / Glossy',
      options: ['20x30', 'Metal', 'Glossy'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170058377,
      title: '20x30 / Metal / Matte',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Matte',
      public_title: '20x30 / Metal / Matte',
      options: ['20x30', 'Metal', 'Matte'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170091145,
      title: '20x30 / Metal / Lustre',
      option1: '20x30',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Metal / Lustre',
      public_title: '20x30 / Metal / Lustre',
      options: ['20x30', 'Metal', 'Lustre'],
      price: 35000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170123913,
      title: '20x30 / Framed Triple Matte / Glossy',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Glossy',
      public_title: '20x30 / Framed Triple Matte / Glossy',
      options: ['20x30', 'Framed Triple Matte', 'Glossy'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170156681,
      title: '20x30 / Framed Triple Matte / Matte',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Matte',
      public_title: '20x30 / Framed Triple Matte / Matte',
      options: ['20x30', 'Framed Triple Matte', 'Matte'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170189449,
      title: '20x30 / Framed Triple Matte / Lustre',
      option1: '20x30',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 20x30 / Framed Triple Matte / Lustre',
      public_title: '20x30 / Framed Triple Matte / Lustre',
      options: ['20x30', 'Framed Triple Matte', 'Lustre'],
      price: 37500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170222217,
      title: '24x36 / Photo Pearl Paper / Glossy',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Glossy',
      public_title: '24x36 / Photo Pearl Paper / Glossy',
      options: ['24x36', 'Photo Pearl Paper', 'Glossy'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170254985,
      title: '24x36 / Photo Pearl Paper / Matte',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Matte',
      public_title: '24x36 / Photo Pearl Paper / Matte',
      options: ['24x36', 'Photo Pearl Paper', 'Matte'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170287753,
      title: '24x36 / Photo Pearl Paper / Lustre',
      option1: '24x36',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Photo Pearl Paper / Lustre',
      public_title: '24x36 / Photo Pearl Paper / Lustre',
      options: ['24x36', 'Photo Pearl Paper', 'Lustre'],
      price: 32500,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170320521,
      title: '24x36 / Metal / Glossy',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Glossy',
      public_title: '24x36 / Metal / Glossy',
      options: ['24x36', 'Metal', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170353289,
      title: '24x36 / Metal / Matte',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Matte',
      public_title: '24x36 / Metal / Matte',
      options: ['24x36', 'Metal', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170386057,
      title: '24x36 / Metal / Lustre',
      option1: '24x36',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Metal / Lustre',
      public_title: '24x36 / Metal / Lustre',
      options: ['24x36', 'Metal', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170418825,
      title: '24x36 / Framed Triple Matte / Glossy',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Glossy',
      public_title: '24x36 / Framed Triple Matte / Glossy',
      options: ['24x36', 'Framed Triple Matte', 'Glossy'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170451593,
      title: '24x36 / Framed Triple Matte / Matte',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Matte',
      public_title: '24x36 / Framed Triple Matte / Matte',
      options: ['24x36', 'Framed Triple Matte', 'Matte'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170484361,
      title: '24x36 / Framed Triple Matte / Lustre',
      option1: '24x36',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 24x36 / Framed Triple Matte / Lustre',
      public_title: '24x36 / Framed Triple Matte / Lustre',
      options: ['24x36', 'Framed Triple Matte', 'Lustre'],
      price: 50000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170549897,
      title: '30x45 / Photo Pearl Paper / Glossy',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Glossy',
      public_title: '30x45 / Photo Pearl Paper / Glossy',
      options: ['30x45', 'Photo Pearl Paper', 'Glossy'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170648201,
      title: '30x45 / Photo Pearl Paper / Matte',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Matte',
      public_title: '30x45 / Photo Pearl Paper / Matte',
      options: ['30x45', 'Photo Pearl Paper', 'Matte'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170713737,
      title: '30x45 / Photo Pearl Paper / Lustre',
      option1: '30x45',
      option2: 'Photo Pearl Paper',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Photo Pearl Paper / Lustre',
      public_title: '30x45 / Photo Pearl Paper / Lustre',
      options: ['30x45', 'Photo Pearl Paper', 'Lustre'],
      price: 45000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170746505,
      title: '30x45 / Metal / Glossy',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Glossy',
      public_title: '30x45 / Metal / Glossy',
      options: ['30x45', 'Metal', 'Glossy'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170812041,
      title: '30x45 / Metal / Matte',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Matte',
      public_title: '30x45 / Metal / Matte',
      options: ['30x45', 'Metal', 'Matte'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170877577,
      title: '30x45 / Metal / Lustre',
      option1: '30x45',
      option2: 'Metal',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Metal / Lustre',
      public_title: '30x45 / Metal / Lustre',
      options: ['30x45', 'Metal', 'Lustre'],
      price: 65000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907170943113,
      title: '30x45 / Framed Triple Matte / Glossy',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Glossy',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Glossy',
      public_title: '30x45 / Framed Triple Matte / Glossy',
      options: ['30x45', 'Framed Triple Matte', 'Glossy'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907171008649,
      title: '30x45 / Framed Triple Matte / Matte',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Matte',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Matte',
      public_title: '30x45 / Framed Triple Matte / Matte',
      options: ['30x45', 'Framed Triple Matte', 'Matte'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
    {
      id: 31907171074185,
      title: '30x45 / Framed Triple Matte / Lustre',
      option1: '30x45',
      option2: 'Framed Triple Matte',
      option3: 'Lustre',
      sku: '',
      requires_shipping: false,
      taxable: false,
      featured_image: null,
      available: true,
      name: 'Peter Iredale - 30x45 / Framed Triple Matte / Lustre',
      public_title: '30x45 / Framed Triple Matte / Lustre',
      options: ['30x45', 'Framed Triple Matte', 'Lustre'],
      price: 75000,
      weight: 0,
      compare_at_price: null,
      inventory_management: null,
      barcode: '',
      requires_selling_plan: false,
      selling_plan_allocations: [],
    },
  ],
  images: [
    'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
  ],
  featured_image:
    'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
  options: ['Size', 'Material', 'Finish'],
  media: [
    {
      alt: null,
      id: 6302027022473,
      position: 1,
      preview_image: {
        aspect_ratio: 0.67,
        height: 2048,
        width: 1365,
        src:
          'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
      },
      aspect_ratio: 0.67,
      height: 2048,
      media_type: 'image',
      src:
        'https://cdn.shopify.com/s/files/1/0246/0201/7873/products/DeathDunesCody_2048x2048.jpg?v=1572829346',
      width: 1365,
    },
  ],
  requires_selling_plan: false,
  selling_plan_groups: [],
  content:
    '<meta charset="utf-8">\n<div class="sm-image-metadata-caption" data-elem-id="imagemetadata_caption_text">The remains of a ship from the 1920s after it ran ashore in Northern Oregon.</div>\n<div class="sm-image-metadata-keywords"></div>',
  selected: {
    id: 31907169009801,
    title: '8x12 / Photo Pearl Paper / Glossy',
    option1: '8x12',
    option2: 'Photo Pearl Paper',
    option3: 'Glossy',
    sku: '',
    requires_shipping: false,
    taxable: false,
    featured_image: null,
    available: true,
    name: 'Peter Iredale - 8x12 / Photo Pearl Paper / Glossy',
    public_title: '8x12 / Photo Pearl Paper / Glossy',
    options: ['8x12', 'Photo Pearl Paper', 'Glossy'],
    price: 9000,
    weight: 0,
    compare_at_price: null,
    inventory_management: null,
    barcode: '',
    requires_selling_plan: false,
    selling_plan_allocations: [],
  },
  optionsWithValues: [
    {
      name: 'Size',
      position: 1,
      values: ['8x12', '12x18', '16x24', '20x30', '24x36', '30x45'],
    },
    {
      name: 'Material',
      position: 2,
      values: ['Photo Pearl Paper', 'Metal', 'Framed Triple Matte'],
    },
    {
      name: 'Finish',
      position: 3,
      values: ['Glossy', 'Matte', 'Lustre'],
    },
  ],
}

const rooms = [
  // {
  //   title: 'bedroom',
  //   defaultHeight: 720,
  //   defaultWidth: 1080,
  //   defaultRatio: 1.5,
  //   verticalCenter: 0.2,
  //   portraitVerticalCenter: 0.2,
  //   horizontalCenter: 40,
  //   scaleInches: 60,
  //   scalePercent: 0.7,
  //   url:
  //     '//cdn.shopify.com/shopifycloud/shopify/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c.gif',
  // },
  {
    title: 'living',
    defaultHeight: 2000,
    defaultWidth: 3000,
    defaultRatio: 1.5,
    verticalCenter: 0.35,
    portraitVerticalCenter: 0.3,
    horizontalCenter: 50,
    scaleInches: 76,
    scalePercent: 0.4,
    url:
      '//cdn.shopify.com/s/files/1/0246/0201/7873/files/3d-rendering-luxury-classic-wall-in-living-room-wi-LY7VSAN.jpg?v=1618099074',
  },
  // {
  //   title: 'office',
  //   defaultHeight: 1365,
  //   defaultWidth: 2048,
  //   defaultRatio: 1.5,
  //   verticalCenter: 0.2,
  //   portraitVerticalCenter: 0.2,
  //   horizontalCenter: 50,
  //   scaleInches: 25.7,
  //   scalePercent: 0.1,
  //   url: '//cdn.shopify.com/shopifycloud/shopify/assets/no-image-2048-5e88c1b20e087fb7bbe9a3771824e743c244f437e4f8ba93bbf7b11b53f7824c.gif',
  // },
]

export { currentProduct, portraitProduct, rooms }
